const users = [
  {
    id: 1,
    name: "Mohammad Ali",
    img: "https://source.unsplash.com/iEEBWgY_6lA",
    bio: "This is my bio section. Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, dolorem.",
    userName: "@Mohammadali003",
    work_title: "Student",
    city: "Dhaka",
    country: "BD",
    linkString: "https://sites333.netlify.app/",
    following: "240",
    followers: "122",
  },
  {
    id: 2,
    name: "Nazmul Islam",
    img: "https://source.unsplash.com/WNoLnJo7tS8",
    bio: "This is my bio section. Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, dolorem.",
    userName: "@NazmulIslam007",
    work_title: "Web Developer",
    city: "Dhaka",
    country: "BD",
    linkString: "https://sites333.netlify.app/",
    following: "240",
    followers: "122",
  },
  {
    id: 3,
    name: "Zahid Hasan",
    img: "https://source.unsplash.com/ZHvM3XIOHoE",
    bio: "This is my bio section. Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, dolorem.",
    userName: "@Zahidhasan007",
    work_title: "Student",
    city: "Dhaka",
    country: "BD",
    linkString: "https://sites333.netlify.app/",
    following: "240",
    followers: "122",
  },
];

export default users;
