const videos = [
  {
    id: 1,
    name: "Nazmul Islam",
    userName: "@NazmulIslam007",
    description: "Good morning Everyone. Lorem ipsum dolor sit amet consectetur.",
    time: "2h",
    img: "",
    video: "/assets/video1.mp4",
    thumbnail: "/assets/2.jpg",
    comments: 2,
    views: "125k",
    react: 10,
    retweet: 0,
    share: 3,
  },
  {
    id: 2,
    name: "Nazmul Islam",
    userName: "@NazmulIslam007",
    description: "Good morning Everyone. Lorem ipsum dolor sit amet consectetur.",
    time: "2h",
    img: "",
    views: "125k",
    video: "/assets/video.mp4",
    thumbnail: "/assets/3.jpg",
    comments: 2,
    react: 10,
    retweet: 0,
    share: 3,
  },
  {
    id: 3,
    name: "Nazmul Islam",
    userName: "@NazmulIslam007",
    description: "Good morning Everyone. Lorem ipsum dolor sit amet consectetur.",
    time: "2h",
    img: "",
    video: "/assets/video1.mp4",
    thumbnail: "/assets/4.jpg",
    comments: 2,
    views: "125k",
    react: 10,
    retweet: 0,
    share: 3,
  },
  {
    id: 4,
    name: "Nazmul Islam",
    userName: "@NazmulIslam007",
    description: "Good morning Everyone. Lorem ipsum dolor sit amet consectetur.",
    time: "2h",
    img: "",
    views: "125k",
    video: "/assets/video.mp4",
    thumbnail: "/assets/5.jpg",
    comments: 2,
    react: 10,
    retweet: 0,
    share: 3,
  },
];

export default videos;
