export const sidebarTree = [
  {
    key: 1,
    label: 'Dashboard',
    icon: 'fa-solid fa-house',
    link: '/',
    children: [
      {
        key: 1.1,
        label: 'Admin',
        link: 'admin',
      },
      {
        key: 1.2,
        label: 'Student',
        link: 'student',
      },
      {
        key: 1.3,
        label: 'Parents',
        link: 'parents',
      },
    ],
  },
  {
    key: 2,
    label: 'User',
    icon: 'fa-solid fa-users',
    link: '/users',
    children: [],
  },
  {
    key: 3,
    label: 'Categories',
    icon: 'fa-solid fa-list',
    link: '/categories',
    children: [],
  },
  {
    key: 4,
    label: 'Feeds',
    icon: 'fa-solid fa-rss',
    link: '/feeds',
    children: [],
  },
]

export const profileTree = [
  {
    key: 1,
    label: 'Update Profile',
    icon: 'fa-regular fa-user',
    link: 'update_profile',
  },
  {
    key: 2,
    label: 'Change Password',
    icon: 'fas fa-key',
    link: 'update_password',
  },
  {
    key: 3,
    label: 'Linked Devices',
    icon: 'fas fa-desktop',
    link: 'linked_devices',
  },
  {
    key: 4,
    label: 'Logout',
    icon: 'fas fa-power-off',
    link: 'logout',
  },
]
export const demoUsers = [
  {
    _id: '634adf6dca4c597f21539ef4',
    name: 'Jhanker Mahabub',
    email: 'jhankar-mahabub@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/53802153?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee8',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef7',
    name: 'Sunny Sungha',
    email: 'sunny@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/24712956?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee8',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef5',
    name: 'Brad Traversy',
    email: 'traversy@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/5550850?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee9',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef3',
    name: 'Sumit Saha',
    email: 'sumit-saha@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/73503432?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee9',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539efa',
    name: 'Hasin Hayder',
    email: 'hasin@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/490779?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee6',
        addressLine: 'Gulshan 2',
        postCode: '1307',
        city: 'Gulshan',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef6',
    name: 'Fayzul Karim',
    email: 'fayzul@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/497812?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee6',
        addressLine: 'Gulshan 2',
        postCode: '1307',
        city: 'Gulshan',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef2',
    name: 'Nazmul Huda',
    email: 'nazmul@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/58470993',
    address: [
      {
        _id: '634adf6dca4c597f21539ee7',
        addressLine: 'Banani',
        postCode: '1203',
        city: 'Mohakhali',
        country: 'Bangladesh',
      },
    ],
    roles: ['admin'],
  },
  {
    _id: '634adf6eca4c597f21539f0c',
    name: 'Jhanker Mahabub',
    email: 'jhankar-mahabub@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/53802153?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eef',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f0b',
    name: 'Sumit Saha',
    email: 'sumit-saha@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/73503432?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eef',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef8',
    name: 'Adrian Twrag',
    email: 'adrian@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/22957728?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee8',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f0d',
    name: 'Brad Traversy',
    email: 'traversy@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/5550850?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eee',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6dca4c597f21539ef9',
    name: 'Tanvir Hasan',
    email: 'tanvir@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/2250509?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539ee9',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f0a',
    name: 'Nazmul Huda',
    email: 'nazmul@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/58470993',
    address: [
      {
        _id: '634adf6dca4c597f21539eef',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f0e',
    name: 'Fayzul Karim',
    email: 'fayzul@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/497812?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eef',
        addressLine: 'BCS Computer City',
        postCode: '1207',
        city: 'Agargaon',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f10',
    name: 'Adrian Twrag',
    email: 'adrian@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/22957728?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eee',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f0f',
    name: 'Sunny Sungha',
    email: 'sunny@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/24712956?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eed',
        addressLine: 'Banani',
        postCode: '1203',
        city: 'Mohakhali',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f12',
    name: 'Hasin Hayder',
    email: 'hasin@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/490779?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eec',
        addressLine: 'Gulshan 2',
        postCode: '1307',
        city: 'Gulshan',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
  {
    _id: '634adf6eca4c597f21539f11',
    name: 'Tanvir Hasan',
    email: 'tanvir@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/2250509?v=4',
    address: [
      {
        _id: '634adf6dca4c597f21539eee',
        addressLine: 'Taltola, Mirpur Road',
        postCode: '1204',
        city: 'Mirpur',
        country: 'Bangladesh',
      },
    ],
    roles: ['user'],
  },
]
export const dashboardDemoAmounts = [
  {
    title: 'Revenue',
    amount: '$21827.13',
    range: 'vs 3 months prior to 26 sep',
    percentage: 11.4,
  },
  {
    title: 'Orders',
    amount: '1,758',
    range: 'vs 3 months prior to 26 sep',
    percentage: -3.2,
  },
  {
    title: 'Purchases',
    amount: '$7,249.31',
    range: 'vs 3 months prior to 26 sep',
    percentage: 5.7,
  },
]
export const latestOrdersDemo = [
  {
    order: '#123',
    status: 'paid',
    date: Date.now() - 10000,
    customer: 'Habibur Rahman',
    total: '$400.00',
  },
  {
    order: '#345',
    status: 'paid',
    date: Date.now() - 30000,
    customer: 'Moshiur Rahman',
    total: '$60.00',
  },
  {
    order: '#986',
    status: 'pending',
    date: Date.now() - 90000,
    customer: 'Ahmed Jubayer',
    total: '$90.00',
  },
  {
    order: '#124',
    status: 'failed',
    date: Date.now() - 40000,
    customer: 'Fayez Ahmed',
    total: '$80.00',
  },
  {
    order: '#431',
    status: 'paid',
    date: Date.now() - 50000,
    customer: 'Abdulla Mamun',
    total: '$180.00',
  },
  {
    order: '#845',
    status: 'failed',
    date: Date.now() - 60000,
    customer: 'Hasin Hyder',
    total: '$18.00',
  },
  {
    order: '#423',
    status: 'paid',
    date: Date.now() - 70000,
    customer: 'Hafizul Islam',
    total: '$88.00',
  },
]
export const topSellingDemo = [
  {
    image: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    product: 'Polo Shirt',
    quantity: '120',
  },
  {
    image: 'https://i.ibb.co/vvCq2zS/IMG-5202-3-768x768.webp',
    product: 'Full Sleve Shirt',
    quantity: '110',
  },
  {
    image: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    product: 'Grammen Full Shirt',
    quantity: '97',
  },
  {
    image: 'https://i.ibb.co/vvCq2zS/IMG-5202-3-768x768.webp',
    product: 'Casual Shirt',
    quantity: '70',
  },
  {
    image: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    product: 'Denim Shirt',
    quantity: '30',
  },
  {
    image: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    product: 'Black T Shirt',
    quantity: '5',
  },
]
export const userListDemo = [
  {
    name: 'Jahid Hasan',
    email: 'jahid@gmai.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'admin',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rasel Ahmed',
    email: 'rasel@gmail.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'user',
    bio: '',
    location: 'dhaka',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Nasir',
    email: 'nasir@gmail.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'user',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    name: 'Robel',
    email: 'robel@gmail.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'user',
    bio: '',
    location: 'bhola',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'John week',
    email: 'john@gmail.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'user',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Jahid Hasan',
    email: 'jahid@gmai.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'admin',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Jahid Hasan',
    email: 'jahid@gmai.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'admin',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Jahid Hasan',
    email: 'jahid@gmai.com',
    avatar: 'https://i.ibb.co/TL2zPNG/IMG-6217-inn-768x768.webp',
    type: 'admin',
    bio: '',
    location: 'mymensingh',
    bgImage: '',
    followerCount: 2323,
    followingCount: 343,
    bookmarkCount: 323,
    favoriteCount: 2323,
    noteCount: 23,
    shareCount: 233,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const userImages = [
  'https://avatars.githubusercontent.com/u/53802153?v=4',
  'https://avatars.githubusercontent.com/u/24712956?v=4',
  'https://avatars.githubusercontent.com/u/5550850?v=4',
  'https://avatars.githubusercontent.com/u/73503432?v=4',
  'https://avatars.githubusercontent.com/u/490779?v=4',
  'https://avatars.githubusercontent.com/u/497812?v=4',
  'https://avatars.githubusercontent.com/u/58470993',
  'https://avatars.githubusercontent.com/u/53802153?v=4',
  'https://avatars.githubusercontent.com/u/73503432?v=4',
  'https://avatars.githubusercontent.com/u/22957728?v=4',
  'https://avatars.githubusercontent.com/u/5550850?v=4',
  'https://avatars.githubusercontent.com/u/2250509?v=4',
  'https://avatars.githubusercontent.com/u/58470993',
  'https://avatars.githubusercontent.com/u/497812?v=4',
  'https://avatars.githubusercontent.com/u/22957728?v=4',
  'https://avatars.githubusercontent.com/u/24712956?v=4',
  'https://avatars.githubusercontent.com/u/490779?v=4',
  'https://avatars.githubusercontent.com/u/2250509?v=4',
]

export const foodImages = [
  'https://i.ibb.co/fNTFLR1/food-1.jpg',
  'https://i.ibb.co/B3mxDWg/food-2.jpg',
  'https://i.ibb.co/0DS9wzM/food-3.jpg',
  'https://i.ibb.co/GdqBXhm/food-4.jpg',
  'https://i.ibb.co/gVDc9Fv/food-5.jpg',
  'https://i.ibb.co/1sDD81S/food-6.jpg',
  'https://i.ibb.co/84TmVs3/food-7.jpg',
  'https://i.ibb.co/7vLTNvq/food-8.jpg',
  'https://i.ibb.co/5Ty9QHx/food-9.jpg',
  'https://i.ibb.co/H4HtJ8Y/food-10.jpg',
  'https://i.ibb.co/FwPW3fj/food-11.jpg',
  'https://i.ibb.co/bsd3gDL/food-12.jpg',
]

//
export const CategoryDemo = [
  {
    id: 1,
    name: 'Food',
    code: 232,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: 'Food 1',
    code: 232,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: 'Food 2',
    code: 232,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

//
export const statusColor = {
  paid: 'success',
  pending: 'warning',
  failed: 'error',
  due: 'error',
}
// Product Image Upload Configuration file
export const drugAndDropConfig = {
  title: 'Drop files here or Click to browse',
  accept: 'image/png, image/jpg, image/jpeg',
  maxFileSize: 2097152,
}
