const DummyData = {}

DummyData.users = [
  {
    name: 'Nazmul Huda',
    email: 'nazmul@gmail.com',
    password: 'Password@1234',
    type: 'admin',
    bio: 'Dynamic Response Facilitator',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Rashadul Alam',
    email: 'rashadul@gmail.com',
    password: 'Password@1234',
    type: 'user',
    bio: 'Direct Markets Specialist',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Kumar',
    email: 'kumar@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Senior Metrics Associate',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Dassimon',
    email: 'dassimon@gmail.com',
    password: 'Password@1234',
    type: 'media',
    bio: 'Legacy Quality Associate',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Brad Traversy',
    email: 'traversy@gmail.com',
    password: 'Password@1234',
    type: 'list',
    bio: 'Regional Research Specialist',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Fayzul Karim',
    email: 'fayzul@gmail.com',
    password: 'Password@1234',
    type: 'media',
    bio: 'Principal Tactics Liaison',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Sunny Sungha',
    email: 'sunny@gmail.com',
    password: 'Password@1234',
    type: 'list',
    bio: 'Customer Communications Specialist',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Adrian Twrag',
    email: 'adrian@gmail.com',
    password: 'Password@1234',
    type: 'media',
    bio: 'Forward Data Facilitator',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Tanvir Hasan',
    email: 'tanvir@gmail.com',
    password: 'Password@1234',
    type: 'list',
    bio: 'Chief Program Developer',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Hasin Hayder',
    email: 'hasin@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Dynamic Division Supervisor',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Hafizul Hayder',
    email: 'hafuzul@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Forward Solutions Planner',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Tonmoy',
    email: 'tonmoy@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'District Mobility Manager',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Abdul Ahad',
    email: 'ahad@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Human Group Coordinator',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Mr Alauddin',
    email: 'alauddin@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Forward Optimization Executive',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Hafuzur Babu',
    email: 'babu@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'Legacy Identity Representative',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
  {
    name: 'Jahid Hasan',
    email: 'jahid@gmail.com',
    password: 'Password@1234',
    type: 'app',
    bio: 'National Functionality Supervisor',
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    avatar: 'avatar.png',
    backgroundImage: 'banner.jpg',
    followerCount: 0,
    followingCount: 0,
    bookmarkCount: 0,
    favoriteCount: 0,
    noteCount: 0,
    shareCount: 0,
    active: true,
  },
]

DummyData.places = [
  '4d904ec81d06b1f7ae6c713b',
  '4d25c4ff38d0236afb73eeb6',
  '5133c4bbe4b09cc36da0afd2',
  '4c03a9019a7920a14225d079',
  '4d4ba488c87b54819f14c688',
  '4d6dcef924b56ea89bbcf7fb',
  '4b92802ff964a5209cfe33e3',
  '4da9a8edfa8cc764971f073d',
  '4e4657fc7d8b91a0658d1ee3',
  '54831bc2498eb82fd620c978',
]

DummyData.feeds = [
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Hiking Adventure',
    description: 'Exploring the scenic mountain trails.',
    link: 'https://example.com/hike',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Coffee Chat',
    description:
      'Sipping coffee and having a cozy conversation at the local cafe.',
    link: 'https://example.com/cafe',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Art Exhibition',
    description: 'Admiring the latest art pieces at the museum.',
    link: 'https://example.com/museum',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Botanical Garden Visit',
    description: 'Strolling through beautiful botanical gardens.',
    link: 'https://example.com/garden',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Live Music Night',
    description: 'Attending a live concert at the grand concert hall.',
    link: 'https://example.com/concert',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Picnic in Central Park',
    description:
      'Having a relaxing picnic surrounded by the beauty of Central Park.',
    link: 'https://example.com/central-park-picnic',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Broadway Lights',
    description:
      'Experiencing the vibrant energy of Times Square and its Broadway lights.',
    link: 'https://example.com/times-square-broadway',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Walk Across the Brooklyn Bridge',
    description:
      'Taking a scenic walk across the iconic Brooklyn Bridge with stunning views of Manhattan.',
    link: 'https://example.com/brooklyn-bridge-walk',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Art Exploration at MoMA',
    description:
      'Exploring contemporary art at the Museum of Modern Art (MoMA).',
    link: 'https://example.com/moma-art-exploration',
  },
  {
    location: {
      name: 'Dhaka',
      type: 'Point',
      coordinates: [40.7128, -74.006],
    },
    title: 'Observation Deck at Empire State Building',
    description:
      'Taking in panoramic views of New York City from the observation deck of the Empire State Building.',
    link: 'https://example.com/empire-state-building-view',
  },
]

DummyData.categories = [
  {
    name: 'Restaurant',
    code: 13065,
    active: true,
  },
  {
    name: 'Bar',
    code: 13003,
    active: true,
  },
  {
    name: 'Breakfast',
    code: 13028,
    active: true,
  },
  {
    name: 'Cafe, Coffee, and Tea House',
    code: 13032,
    active: true,
  },
  {
    name: 'Dessert Shop',
    code: 13040,
    active: true,
  },
  {
    name: 'Bakery',
    code: 13002,
    active: true,
  },
]

DummyData.notes = [
  {
    note: 'Absolutely loved the ambiance and decor! A perfect blend of modern and cozy.',
  },
  {
    note: 'The menu is a gastronomic delight! So many unique and delicious options to choose from.',
  },
  {
    note: 'Attentive and friendly staff made the dining experience even more enjoyable. Kudos to the excellent service!',
  },
  {
    note: 'Great options for health-conscious individuals. I appreciated the variety of salads and grilled dishes.',
  },
  {
    note: 'Desserts were a highlight! The presentation and flavors were top-notch. Will definitely be back for more.',
  },
  {
    note: "Ideal spot for a family dinner. The kids' menu had plenty of choices, and everyone left happy and satisfied.",
  },
  {
    note: 'A haven for vegetarians! The vegetarian options were creative and full of flavor. Thumbs up!',
  },
  {
    note: 'Romantic atmosphere, perfect for a date night. The candlelit tables and soft music set the mood beautifully.',
  },
]

export default DummyData
